### ISSUE TITLE
CI: Run scorecard workflow only on default branch

### ISSUE THREAD

**Issue by olleolleolle** [FoveaCentral/google_maps_geocoder#143]
# Description

The error message after starting the tool is

>   2024/12/18 08:52:34 creating scorecard entrypoint: validating options: only default branch is supported

# Steps to Reproduce

1. See https://github.com/FoveaCentral/google_maps_geocoder/actions/runs/12389485768/job/34582596749

# Solution idea

Use an `if: github.ref_name == github.event.repository.default_branch` on the step.

**Comment by ivanoblomov** [comment]
Good catch! Happy to take this on tomorrow if you haven't already.
