### ISSUE TITLE
Attain CII Best Practices: Silver

### ISSUE THREAD

**Issue by ivanoblomov** [FoveaCentral/google_maps_geocoder#63]
# Task

## Goal

Attain silver-level CII Best Practices.

## Description

Improve software and project quality by observing [silver-level CII Best Practices](https://bestpractices.coreinfrastructure.org/en/projects/92?criteria_level=1).

## Success Criteria

The CII Best Practices badge shows the silver level.

**Comment by ivanoblomov** [comment]
@olleolleolle for [Project oversight: The project SHOULD have a "bus factor" of 2 or more](https://bestpractices.coreinfrastructure.org/en/projects/92?criteria_level=1) of the Best Practices, do you feel comfortable with us asserting:

> Roderick Monje and Olle Jonsson are all very familiar with the software and could easily continue its maintenance if necessary. A few other people have contributed and they could also probably maintain it if absolutely necessary. See [GitHub contributors statistics](https://github.com/GoogleMapsGeocoder/google_maps_geocoder/graphs/contributors) for the latest statistics on contributors.

And if you don't happen to, could you indulge me, at your leisure, of course, with a [security review](https://bestpractices.coreinfrastructure.org/en/projects/92?criteria_level=2#security) which would not only get us that much further toward Gold Best Practices certification, but also familiarize yourself with the code too? ;)

**Comment by ivanoblomov** [comment]
@olleolleolle I added you to the [governance model](https://github.com/GoogleMapsGeocoder/google_maps_geocoder/wiki/Governance). Open to your edits.

**Comment by olleolleolle** [comment]
I enjoy using https://www.contributor-covenant.org/version/2/1/code_of_conduct/ for a Code of Conduct, as it takes a bit more responsibility.
